peer_labels: false
duplicated_issues: false
scheduled_tasks:
  chime_on_stalled:
    if_type: pr
    if_state: open
    if_updated: "10 days"
    comment: "@${ASSIGNEE} Ya van diez días desde la última vez"
