name: 'Cierra issues y PRs antiguos'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-pr-label: 'needs decision'
          stale-issue-label: 'stale'
          days-before-issue-stale: 10
          days-before-pr-stale: 7
          days-before-pr-close: 21
          stale-issue-message: 'Hola, este issue lleva un tiempo sin novedades. Estás trabajando todavía?\nSi necesitas ayuda :sos: no dudes en contactarnos en nuestro grupo de Telegram.'
          stale-pr-message: 'Hola, este PR lleva un tiempo sin novedades. Vamos a pedir a un admin de nuestro equipo que decida si alguien más puede finalizar este PR o si tenemos que cancelarlo.\nPor favor avisanos en caso de que aún puedas tomarte el tiempo para terminarlo'
